const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('jarvis', {
  status: () => ipcRenderer.invoke('status'),
  history: () => ipcRenderer.invoke('history'),
  send: t => ipcRenderer.invoke('send', t),
  cancel: () => ipcRenderer.invoke('cancel'),
  stats: () => ipcRenderer.invoke('stats'),
  memories: () => ipcRenderer.invoke('memories'),
  voice: on => ipcRenderer.invoke('voice', on),
  say: t => ipcRenderer.invoke('say', t),
  onAudio: f => ipcRenderer.on('audio', (_e, a) => f(a)),
  transcribe: pcm => ipcRenderer.invoke('transcribe', pcm),
  onTool: f => ipcRenderer.on('tool', (_e, t) => f(t)),
  onReminder: f => ipcRenderer.on('reminder', (_e, r) => f(r)),
  onUi: f => ipcRenderer.on('ui', (_e, a) => f(a)),
  onNowPlaying: f => ipcRenderer.on('nowplaying', (_e, n) => f(n)),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: s => ipcRenderer.invoke('settings:set', s),
  connect: which => ipcRenderer.invoke('connect:' + (['twitch', 'nanoleaf'].includes(which) ? which : 'spotify')),
  clips: {
    pick: () => ipcRenderer.invoke('clips:pick'),
    caption: o => ipcRenderer.invoke('clips:caption', o),
    export: o => ipcRenderer.invoke('clips:export', o),
    facecam: o => ipcRenderer.invoke('clips:facecam', o),
    reveal: f => ipcRenderer.invoke('clips:reveal', f),
    moments: f => ipcRenderer.invoke('clips:moments', f),
    thumb: o => ipcRenderer.invoke('clips:thumb', o),
    download: o => ipcRenderer.invoke('clips:download', o),
    onStatus: f => ipcRenderer.on('clips:status', (_e, s) => f(s)),
    onProgress: f => ipcRenderer.on('clips:progress', (_e, p) => f(p)),
  },
  onNotice: f => ipcRenderer.on('notice', (_e, m) => f(m)),
  quick: (action, arg) => ipcRenderer.invoke('pc:quick', action, arg),
  onTwitch: f => ipcRenderer.on('twitch', (_e, s) => f(s)),
  onPtt: f => ipcRenderer.on('ptt', () => f()),
  onAnim: f => ipcRenderer.on('anim', (_e, a) => f(a)),
  onPttHold: f => ipcRenderer.on('ptt-hold', () => f()),
  onDelta: f => ipcRenderer.on('delta', (_e, t) => f(t)),
  core: c => ipcRenderer.send('core', c),
  onCore: f => ipcRenderer.on('core', (_e, c) => f(c)),
  onDone: f => ipcRenderer.on('done', (_e, r) => f(r)),
});
